#!/usr/bin/env python

# upm - undo p to p'

# Copyright (c) 2015 Jason Schulz <https://github.com/uxcn>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# author: jason

import sys

import os
import os.path

__program__ = 'upm'
__version__ = '0.1'
__author__  = 'Jason Schulz'
__doc__     = 'upm [-a] <p> [p...]'

c = sys.argv[0]
a = False

def usage():
    print(__doc__)
    sys.exit(1)

def on_error(e, x=1):
    if not e is None:
        print('%s: %s' % (c, e), file=sys.stderr)

    sys.exit(x)

if len(sys.argv) == 1:
    usage()

if sys.argv[1] == '-a':

    if len(sys.argv) == 2:
        usage()

    a = True

pms = sys.argv[1:] if not a else sys.argv[2:]

for pm in pms:

    pm = os.path.abspath(pm)

    p = pm

    if a:
        p = p.rstrip('\'')
    elif p.endswith('\''):
        p = p[0:-1]

    if os.path.lexists(p):

        prompt = '%s: overwrite (%s)? ' % (c, p)

        if input(prompt) not in ['Y', 'y']:
            continue

    try:
        os.rename(pm, p)
    except OSError as e:
        on_error('%s (%s -> %s)' % (e.strerror, pm, p))

# vim:ft=python:et:ts=4:sts=4:sw=4:tw=80
